// <auto-generated />
using ConsoleApp2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20230911162127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ConsoleApp2.Blog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("TabularHiLo:UseHiLo", true);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b
                        .HasAnnotation("TabularHiLo:IncrementBy", 10L)
                        .HasAnnotation("TabularHiLo:SequenceName", "Blog")
                        .HasAnnotation("TabularHiLo:StartsAt", 1L)
                        .HasAnnotation("TabularHiLo:UseHiLo", true);
                });

            modelBuilder.Entity("ConsoleApp2.HiLo.Metadata.SequenceTable", b =>
                {
                    b.Property<string>("SequenceName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncrementBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("SequenceName");

                    b.ToTable("__EFCoreHiLoSequences");

                    b.HasData(
                        new
                        {
                            SequenceName = "Blog",
                            CurrentValue = 1L,
                            IncrementBy = 10L
                        },
                        new
                        {
                            SequenceName = "Post",
                            CurrentValue = 1L,
                            IncrementBy = 10L
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("TabularHiLo:UseHiLo", true);

                    b.Property<long>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b
                        .HasAnnotation("TabularHiLo:IncrementBy", 10L)
                        .HasAnnotation("TabularHiLo:SequenceName", "Post")
                        .HasAnnotation("TabularHiLo:StartsAt", 1L)
                        .HasAnnotation("TabularHiLo:UseHiLo", true);
                });

            modelBuilder.Entity("ConsoleApp2.Post", b =>
                {
                    b.HasOne("ConsoleApp2.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("ConsoleApp2.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
